### ISSUE TITLE
Create a score

### ISSUE THREAD

**Issue by impactcolor** [FlatIO/api-client-python#20]
When following the example (exactly, except for the access_token being set to my personal access token.

```
configuration = flat_api.Configuration(
    host = "https://api.flat.io/v2"
)
configuration.access_token = 'myAccesstokengeneratedOnApps'

# Enter a context with an instance of the API client
with flat_api.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = flat_api.ScoreApi(api_client)
    body = flat_api.ScoreCreation() # ScoreCreation | 

    try:
        # Create a new score
        api_response = api_instance.create_score(body)
        pprint(api_response)
    except ApiException as e:
        print("Exception when calling ScoreApi->create_score: %s\n" % e)
```

This kicks out an error:
HTTP response headers: HTTPHeaderDict({'Date': 'Sun, 07 May 2023 03:57:23 GMT', 'Content-Type': 'application/json; charset=utf-8', 'Content-Length': '123', 'Connection': 'keep-alive', 'X-Flat-Request-Id': '6f7604ba-9afc-4d93-beeb-ce8438621afa', 'Access-Control-Allow-Headers': 'Origin, Accept, Content-Type, Authorization, X-Requested-With, X-Flat-Client, X-Flat-Request-As, baggage, sentry-trace', 'Access-Control-Expose-Headers': 'Link, X-Flat-Access-Token, X-Flat-User, X-Flat-Organization, X-Flat-Score-Revision, X-Flat-Score-Revision-Date', 'Access-Control-Allow-Origin': '*', 'ETag': 'W/"7b-ZZRoYECfxY1H1o4dShd33vacrx8"'})
HTTP response body: {"message":"privacy: must have required property 'privacy'","code":"CLIENT_INPUT_ERROR","location":"body","path":"privacy"}

Any idea what's incorrect in this call?

**Comment by gierschv** [comment]
Hello,

Thank you for your feedback. [This endpoint](https://flat.io/developers/api/reference/#tag/Score/operation/createScore) requires a `privacy` param, which you can set to `private` by default.

I will check to update the client docs shortly.

Vincent

**Comment by gierschv** [comment]
The API has been updated so `privacy`  is now optional and private by default. We released an API update and SDK update as well. Make sure you have a score file or builder data when using this endpoint, the docs are available here: https://flat.io/developers/api/reference/#tag/Score/operation/createScore
