### ISSUE TITLE
No module named 'flat_api.model'

### ISSUE THREAD

**Issue by impactcolor** [FlatIO/api-client-python#32]
When running the example indicated in create_score:
`import time
import flat_api
import os
from flat_api.api import score_api
from flat_api.model.score_creation import ScoreCreation
from flat_api.model.score_details import ScoreDetails
from flat_api.model.flat_error_response import FlatErrorResponse`

I get the error mentioned in the title: No module named 'flat_api.model'

I pip installed both examples in the Code example.  pip install flat_api  and also from the git repo.
Any idea how to resolve this?

**Comment by gierschv** [comment]
Hey!

I just tried a sample without any issues using the latest released on pip. There was a missing import in the generated docs, but that seems to be working fine for me on the client part:

**NOTE: this sample doesn't load or push a valid file - API returns `SCORE_UNSUPPORTED_FORMAT` with `data_example`*

```python

import time
import flat_api
from flat_api.api import score_api
from flat_api.model.score_creation import ScoreCreation
from flat_api.model.score_details import ScoreDetails
from flat_api.model.score_privacy import ScorePrivacy
from flat_api.model.flat_error_response import FlatErrorResponse
from pprint import pprint

configuration = flat_api.Configuration(
    host = "https://api.flat.io/v2"
)
configuration.access_token = 'xxx'

# Enter a context with an instance of the API client
with flat_api.ApiClient(configuration) as api_client:
    # Create an instance of the API class
    api_instance = score_api.ScoreApi(api_client)
    body = ScoreCreation(
        title="title_example",
        privacy=ScorePrivacy("private"),
        filename="filename_example",
        data="data_example",
        data_encoding="base64"
    ) # ScoreCreation | 

    # example passing only required values which don't have defaults set
    try:
        # Create a new score
        api_response = api_instance.create_score(body)
        pprint(api_response)
    except flat_api.ApiException as e:
        print("Exception when calling ScoreApi->create_score: %s\n" % e)
```

What's your python version / module version you have installed?

**Comment by impactcolor** [comment]
@gierschv Thank you! (i'm also testing the js sdk)
3.9 
when running pip freeze I get:
flat-api @ git+https://github.com/FlatIO/api-client-python.git@225c2cceaff762c88efd5cf0e64737df82ec6b27
